# Generated by Django 4.1.2 on 2022-11-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitday',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='start_time',
        ),
    ]
