# Generated by Django 4.1.2 on 2022-11-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitDay',
        ),
    ]
