# Generated by Django 4.1.2 on 2022-11-11 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0002_remove_visitday_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitday',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitday',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='visitday',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
