# Generated by Django 4.1.2 on 2022-11-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visitday_company_name_visitday_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='weekday',
        ),
        migrations.AddField(
            model_name='visitday',
            name='weekday',
            field=models.ManyToManyField(to='visits.weekday'),
        ),
    ]
