# Generated by Django 4.1.2 on 2022-11-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_weekday_remove_visitday_weekday_visitday_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='weekday',
        ),
        migrations.AddField(
            model_name='weekday',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='weekday',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
