# Generated by Django 4.1.2 on 2022-11-10 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0004_alter_visitday_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitday',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_days', to=settings.AUTH_USER_MODEL),
        ),
    ]
