# Generated by Django 4.1.2 on 2022-11-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_timesheet_remove_visitday_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='user',
            field=models.ManyToManyField(to='visits.visitday'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='weekday',
            field=models.ManyToManyField(to='visits.weekday'),
        ),
    ]
