# Generated by Django 4.1.2 on 2022-11-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_timesheet_user_timesheet_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitday',
            name='weekday',
            field=models.ManyToManyField(through='visits.Timesheet', to='visits.weekday'),
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='weekday',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visits.visitday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='weekday',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='visits.weekday'),
            preserve_default=False,
        ),
    ]
