# Generated by Django 4.1.2 on 2022-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_visitday_weekday_remove_timesheet_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
