# Generated by Django 4.1.2 on 2022-11-11 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0008_remove_weekday_end_time_remove_weekday_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='weekday',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='company_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='time_sheet', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VisitDay',
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
