# Generated by Django 4.1.2 on 2022-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_remove_timesheet_weekday_timesheet_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thrusday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='1', max_length=20),
        ),
    ]
