# Generated by Django 4.1.2 on 2022-11-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_timesheet_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='company_name',
        ),
    ]
