# Generated by Django 4.1.2 on 2022-11-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_timesheet_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thrusday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='Monday', max_length=20),
        ),
    ]
