# Generated by Django 4.1.2 on 2022-11-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0018_alter_timesheet_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='user',
            new_name='customer',
        ),
    ]
