# Generated by Django 4.1.2 on 2022-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0022_rename_visit_visitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
