# Generated by Django 4.1.2 on 2022-11-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0025_remove_visitlog_company_name_visitlog_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='notes',
        ),
    ]
