# Generated by Django 4.1.2 on 2022-11-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0026_remove_visitlog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
