# Generated by Django 4.1.2 on 2022-11-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0028_timesheet_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='notes',
        ),
    ]
