# Generated by Django 4.1.2 on 2022-11-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0029_remove_timesheet_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=20),
        ),
    ]
