# Generated by Django 4.1.2 on 2022-11-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='notes',
            new_name='message',
        ),
    ]
