# Generated by Django 4.1.2 on 2022-11-16 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0029_remove_timesheet_notes'),
        ('providers', '0002_rename_notes_messages_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_duration', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoice', to=settings.AUTH_USER_MODEL)),
                ('end_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.visitlog')),
                ('start_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_start_visit', to='visits.visitlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_invoice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
