# Generated by Django 4.1.2 on 2022-11-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_invoice_end_visit_alter_invoice_start_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='visit_duration',
        ),
    ]
