# Generated by Django 4.1.2 on 2022-11-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_rename_user_messages_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='provider',
            new_name='user',
        ),
    ]
