# Generated by Django 4.1.2 on 2022-11-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
    ]
