# Generated by Django 4.1.2 on 2022-11-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip',
        ),
    ]
