# Generated by Django 4.1.2 on 2022-11-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_display_name_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.BooleanField(default=False),
        ),
    ]
