# Generated by Django 4.1.2 on 2022-11-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_display_name_user_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer',
            new_name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
