# Generated by Django 4.1.2 on 2022-11-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_city_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
