# Generated by Django 4.1.2 on 2022-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_city_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
